# Generated by Django 2.2 on 2019-10-01 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_maquinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maquinaria', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo_maquinaria',
                'verbose_name_plural': 'Tipo_maquinarias',
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('alq', 'alquilado'), ('dis', 'disponible')], default='dis', max_length=2)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.Tipo_maquinaria')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
            },
        ),
    ]
