# Generated by Django 2.2 on 2019-10-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20190930_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
