# Generated by Django 2.2 on 2019-10-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_maquinaria',
            old_name='nombre_maquinaria',
            new_name='tipo_maquinaria',
        ),
    ]
