# Generated by Django 2.2 on 2019-10-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_auto_20190930_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='nombre',
            field=models.CharField(default='C/F', max_length=13),
        ),
    ]
