# Generated by Django 2.2 on 2019-10-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20190930_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='estado',
            field=models.CharField(choices=[('alq', 'alquilado'), ('dis', 'disponible')], default='dis', max_length=2),
        ),
    ]
