# Generated by Django 2.2 on 2019-10-01 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_maquinaria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinaria',
            name='estado',
            field=models.CharField(choices=[('alq', 'alquilado'), ('dis', 'disponible')], default='dis', max_length=3),
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.Cliente')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquilers',
            },
        ),
    ]
