# Generated by Django 2.2 on 2019-10-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_auto_20190930_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_maquinaria',
        ),
    ]
