# Generated by Django 2.2 on 2019-10-01 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_delete_tipo_maquinaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='tipo',
            new_name='cliente',
        ),
    ]
