# Generated by Django 2.0.13 on 2019-11-17 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maquinaria', models.CharField(max_length=60)),
                ('imagen', models.ImageField(upload_to='images')),
                ('fraccion_tiempo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marca', models.CharField(max_length=40)),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('A', 'Alquilada')], max_length=4)),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Maquinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=30)),
                ('descripcion', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Tipo_Maquinaria',
                'verbose_name_plural': 'Tipo_Maquinarias',
            },
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='tipo_maquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maquinaria.Tipo_Maquinaria'),
        ),
    ]
