# Generated by Django 2.0.13 on 2019-11-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('nit', models.TextField(blank=True, default='C/F')),
                ('direccion', models.TextField(blank=True, default='Ciudad')),
                ('telefono', models.CharField(max_length=16)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
