# Generated by Django 2.0.13 on 2019-11-17 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('maquinaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alquiler', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('re', 'recivida'), ('pa', 'pagada'), ('pr', 'proceso')], default='re', max_length=3)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquilers',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_maquinas', models.PositiveIntegerField(default=1)),
                ('cantidad_horas', models.IntegerField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maquinaria.Maquinaria')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renta.Alquiler')),
            ],
            options={
                'verbose_name': 'Detalle_Alquiler',
                'verbose_name_plural': 'Detalle_Alquilers',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=12)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('pago', models.CharField(choices=[('ef', 'efectivo'), ('cd', 'tarjeta'), ('cq', 'cheque')], max_length=3)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='renta.Alquiler')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.AddField(
            model_name='alquiler',
            name='maquinaria',
            field=models.ManyToManyField(through='renta.Detalle_Alquiler', to='maquinaria.Maquinaria'),
        ),
    ]
